## Ebenezer - 1CR17CS040

In [1]:
import numpy as np
x = np.array(([2, 9], [1, 5], [3, 6]), dtype = float)
y = np.array(([92], [86], [89]), dtype = float)
print("Input:\n",x)
print("Output:\n",y)

Input:
 [[2. 9.]
 [1. 5.]
 [3. 6.]]
Output:
 [[92.]
 [86.]
 [89.]]


In [2]:
c = np.amax(x, axis = 0)
print(c)

[3. 9.]


In [3]:
x = x/c
y = y/100
print("Normalized Input:\n",x)
print("Normalized Output:\n",y)

Normalized Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Normalized Output:
 [[0.92]
 [0.86]
 [0.89]]


In [4]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))
def sigmoid_grad(x):
    return x * (1 - x)
epoch = 1000
eta = 0.1
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

In [5]:
wh = np.random.uniform(size = (input_neurons, hidden_neurons))
print("Weights input to hidden:\n",wh)

Weights input to hidden:
 [[0.78193401 0.43404771 0.13608714]
 [0.16729401 0.78539079 0.38000556]]


In [6]:
bh = np.random.uniform(size = (1, hidden_neurons))
print("Input Bias:\n",bh)

Input Bias:
 [[0.95553775 0.78996106 0.86213394]]


In [7]:
wout = np.random.uniform(size = (hidden_neurons, output_neurons))
print("Weights from hidden to Output Layer:\n",wout)

Weights from hidden to Output Layer:
 [[0.86942546]
 [0.15484712]
 [0.88625814]]


In [8]:
bout = np.random.uniform(size = (1, output_neurons))
print("Output Bias:\n",bout)

Output Bias:
 [[0.99005976]]


In [9]:
for i in range(epoch):
    print("\n\t( EPOCH {} of {} )".format(i+1, epoch))
    h_ip = np.dot(x, wh) + bh
    print("h_ip:\n", h_ip)
    h_act = sigmoid(h_ip)
    o_ip = np.dot(h_act, wout) + bout
    output = sigmoid(o_ip)
    eo = y - output
    out_grad = sigmoid_grad(output)
    d_output = eo * out_grad
    print("Output:\n", d_output)
    eh = d_output.dot(wout.T)
    hidden_grad = sigmoid_grad(h_act)
    d_hidden = eh * hidden_grad
    wout += h_act.T.dot(d_output) * eta
    wh += x.T.dot(d_hidden) * eta


	( EPOCH 1 of 1000 )
h_ip:
 [[1.6441211  1.86471699 1.33286426]
 [1.30912353 1.37097184 1.11861052]
 [1.8490011  1.74760263 1.25155812]]
Output:
 [[-0.00052543]
 [-0.00445347]
 [-0.00255233]]

	( EPOCH 2 of 1000 )
h_ip:
 [[1.64402696 1.86470031 1.33274401]
 [1.30907315 1.37096292 1.11854626]
 [1.84890956 1.74758632 1.2514398 ]]
Output:
 [[-0.00051923]
 [-0.00445139]
 [-0.00254889]]

	( EPOCH 3 of 1000 )
h_ip:
 [[1.64393306 1.86468372 1.33262405]
 [1.3090229  1.37095405 1.11848215]
 [1.84881824 1.7475701  1.25132178]]
Output:
 [[-0.00051301]
 [-0.00444929]
 [-0.00254544]]

	( EPOCH 4 of 1000 )
h_ip:
 [[1.6438394  1.86466722 1.3325044 ]
 [1.30897278 1.37094523 1.11841821]
 [1.84872716 1.74755398 1.25120404]]
Output:
 [[-0.00050677]
 [-0.00444718]
 [-0.00254197]]

	( EPOCH 5 of 1000 )
h_ip:
 [[1.64374598 1.86465083 1.33238505]
 [1.30892278 1.37093646 1.11835443]
 [1.84863631 1.74753795 1.2510866 ]]
Output:
 [[-0.00050052]
 [-0.00444504]
 [-0.00253848]]

	( EPOCH 6 of 1000 )
h_ip:
 [[1.64

 [1.838994   1.74615847 1.23859613]]
Output:
 [[ 0.00038723]
 [-0.00405033]
 [-0.00198205]]

	( EPOCH 134 of 1000 )
h_ip:
 [[1.63378416 1.8632345  1.31964   ]
 [1.30359249 1.37017905 1.11154526]
 [1.83893439 1.74615212 1.23851879]]
Output:
 [[ 0.00039446]
 [-0.00404657]
 [-0.00197715]]

	( EPOCH 135 of 1000 )
h_ip:
 [[1.63372332 1.86322808 1.31956213]
 [1.30355994 1.37017562 1.11150367]
 [1.83887501 1.74614583 1.23844176]]
Output:
 [[ 0.00040169]
 [-0.00404282]
 [-0.00197225]]

	( EPOCH 136 of 1000 )
h_ip:
 [[1.63366273 1.86322172 1.31948458]
 [1.30352753 1.37017222 1.11146225]
 [1.83881587 1.7461396  1.23836504]]
Output:
 [[ 0.00040892]
 [-0.00403905]
 [-0.00196735]]

	( EPOCH 137 of 1000 )
h_ip:
 [[1.63360238 1.86321541 1.31940735]
 [1.30349525 1.37016885 1.11142101]
 [1.83875698 1.74613342 1.23828864]]
Output:
 [[ 0.00041614]
 [-0.00403529]
 [-0.00196244]]

	( EPOCH 138 of 1000 )
h_ip:
 [[1.63354229 1.86320916 1.31933043]
 [1.3034631  1.3701655  1.11137993]
 [1.83869832 1.74612729 1

 [1.8350403  1.74580571 1.23346872]]
Output:
 [[ 0.00093599]
 [-0.00374983]
 [-0.00159925]]

	( EPOCH 212 of 1000 )
h_ip:
 [[1.62975765 1.86287833 1.31449283]
 [1.30143898 1.36998864 1.10879724]
 [1.83499838 1.74580275 1.23341442]]
Output:
 [[ 0.00094269]
 [-0.00374599]
 [-0.00159445]]

	( EPOCH 213 of 1000 )
h_ip:
 [[1.62971508 1.86287536 1.31443854]
 [1.30141622 1.36998705 1.10876827]
 [1.83495667 1.74579983 1.23336039]]
Output:
 [[ 0.00094939]
 [-0.00374214]
 [-0.00158965]]

	( EPOCH 214 of 1000 )
h_ip:
 [[1.62967272 1.86287242 1.31438454]
 [1.30139357 1.36998548 1.10873945]
 [1.83491518 1.74579694 1.23330664]]
Output:
 [[ 0.00095608]
 [-0.0037383 ]
 [-0.00158486]]

	( EPOCH 215 of 1000 )
h_ip:
 [[1.62963059 1.86286951 1.31433081]
 [1.30137104 1.36998393 1.10871078]
 [1.83487389 1.74579408 1.23325317]]
Output:
 [[ 0.00096275]
 [-0.00373446]
 [-0.00158007]]

	( EPOCH 216 of 1000 )
h_ip:
 [[1.62958867 1.86286663 1.31427737]
 [1.30134863 1.36998239 1.10868226]
 [1.83483281 1.74579126 1

 [[ 0.00139113]
 [-0.00348115]
 [-0.00126788]]

	( EPOCH 285 of 1000 )
h_ip:
 [[1.62718715 1.86273248 1.31122765]
 [1.300065   1.3699107  1.10705565]
 [1.83247357 1.74565927 1.23015165]]
Output:
 [[ 0.00139682]
 [-0.0034777 ]
 [-0.00126367]]

	( EPOCH 286 of 1000 )
h_ip:
 [[1.627159   1.86273129 1.31119211]
 [1.30004996 1.36991006 1.10703671]
 [1.83244582 1.74565809 1.23011593]]
Output:
 [[ 0.00140249]
 [-0.00347426]
 [-0.00125947]]

	( EPOCH 287 of 1000 )
h_ip:
 [[1.62713102 1.86273011 1.3111568 ]
 [1.30003501 1.36990943 1.10701789]
 [1.83241823 1.74565693 1.23008043]]
Output:
 [[ 0.00140815]
 [-0.00347082]
 [-0.00125529]]

	( EPOCH 288 of 1000 )
h_ip:
 [[1.62710322 1.86272896 1.31112173]
 [1.30002016 1.36990881 1.1069992 ]
 [1.83239082 1.74565579 1.23004515]]
Output:
 [[ 0.0014138 ]
 [-0.0034674 ]
 [-0.00125111]]

	( EPOCH 289 of 1000 )
h_ip:
 [[1.6270756  1.86272781 1.31108688]
 [1.3000054  1.3699082  1.10698063]
 [1.83236358 1.74565467 1.2300101 ]]
Output:
 [[ 0.00141943]
 [-0.0034


	( EPOCH 356 of 1000 )
h_ip:
 [[1.62559359 1.86268122 1.30923402]
 [1.29921409 1.36988332 1.1059941 ]
 [1.83089531 1.74560862 1.22813225]]
Output:
 [[ 0.00175914]
 [-0.00325412]
 [-0.00099285]]

	( EPOCH 357 of 1000 )
h_ip:
 [[1.62557653 1.86268087 1.30921298]
 [1.29920498 1.36988313 1.10598292]
 [1.83087829 1.74560827 1.22811069]]
Output:
 [[ 0.00176364]
 [-0.0032513 ]
 [-0.00098944]]

	( EPOCH 358 of 1000 )
h_ip:
 [[1.6255596  1.86268052 1.30919212]
 [1.29919595 1.36988295 1.10597183]
 [1.8308614  1.74560792 1.2280893 ]]
Output:
 [[ 0.00176814]
 [-0.00324848]
 [-0.00098605]]

	( EPOCH 359 of 1000 )
h_ip:
 [[1.62554281 1.86268019 1.30917144]
 [1.29918699 1.36988277 1.10596083]
 [1.83084464 1.74560759 1.22806808]]
Output:
 [[ 0.00177261]
 [-0.00324567]
 [-0.00098267]]

	( EPOCH 360 of 1000 )
h_ip:
 [[1.62552615 1.86267985 1.30915093]
 [1.29917811 1.36988259 1.10594993]
 [1.83082801 1.74560726 1.22804703]]
Output:
 [[ 0.00177707]
 [-0.00324287]
 [-0.0009793 ]]

	( EPOCH 361 of 1000 )
h

Output:
 [[ 0.00216421]
 [-0.00299592]
 [-0.00068402]]

	( EPOCH 468 of 1000 )
h_ip:
 [[1.62440903 1.86267086 1.30783137]
 [1.29858353 1.36987779 1.10525145]
 [1.82969255 1.74559832 1.22664816]]
Output:
 [[ 0.00216705]
 [-0.00299408]
 [-0.00068183]]

	( EPOCH 469 of 1000 )
h_ip:
 [[1.62440405 1.86267091 1.3078262 ]
 [1.2985809  1.36987781 1.10524876]
 [1.82968722 1.74559837 1.22664209]]
Output:
 [[ 0.00216988]
 [-0.00299224]
 [-0.00067965]]

	( EPOCH 470 of 1000 )
h_ip:
 [[1.62439915 1.86267096 1.30782114]
 [1.29857831 1.36987784 1.10524612]
 [1.82968198 1.74559842 1.22663613]]
Output:
 [[ 0.00217269]
 [-0.00299042]
 [-0.00067749]]

	( EPOCH 471 of 1000 )
h_ip:
 [[1.62439433 1.86267101 1.30781619]
 [1.29857576 1.36987787 1.10524353]
 [1.82967682 1.74559848 1.22663027]]
Output:
 [[ 0.0021755 ]
 [-0.0029886 ]
 [-0.00067533]]

	( EPOCH 472 of 1000 )
h_ip:
 [[1.6243896  1.86267107 1.30781134]
 [1.29857326 1.3698779  1.10524101]
 [1.82967173 1.74559853 1.22662452]]
Output:
 [[ 0.00217829]
 

 [[1.62423859 1.86267556 1.30770708]
 [1.29849465 1.36988029 1.10518985]
 [1.82949172 1.74560318 1.22645352]]
Output:
 [[ 0.00234011]
 [-0.00288131]
 [-0.00054812]]

	( EPOCH 541 of 1000 )
h_ip:
 [[1.6242386  1.86267563 1.30770849]
 [1.2984947  1.36988032 1.10519068]
 [1.82949124 1.74560324 1.22645389]]
Output:
 [[ 0.00234211]
 [-0.00288   ]
 [-0.00054657]]

	( EPOCH 542 of 1000 )
h_ip:
 [[1.62423868 1.86267569 1.30770999]
 [1.29849477 1.36988036 1.10519154]
 [1.82949082 1.74560331 1.22645433]]
Output:
 [[ 0.00234411]
 [-0.00287869]
 [-0.00054502]]

	( EPOCH 543 of 1000 )
h_ip:
 [[1.62423881 1.86267576 1.30771156]
 [1.29849487 1.36988039 1.10519245]
 [1.82949045 1.74560338 1.22645484]]
Output:
 [[ 0.00234609]
 [-0.00287739]
 [-0.00054349]]

	( EPOCH 544 of 1000 )
h_ip:
 [[1.624239   1.86267582 1.3077132 ]
 [1.29849501 1.36988042 1.1051934 ]
 [1.82949014 1.74560345 1.22645543]]
Output:
 [[ 0.00234806]
 [-0.0028761 ]
 [-0.00054195]]

	( EPOCH 545 of 1000 )
h_ip:
 [[1.62423925 1.86267588 

 [1.82952498 1.74560592 1.22654497]]
Output:
 [[ 0.00242415]
 [-0.00282602]
 [-0.00048283]]

	( EPOCH 588 of 1000 )
h_ip:
 [[1.62429943 1.86267812 1.30785416]
 [1.29852882 1.36988164 1.10527177]
 [1.82952683 1.74560596 1.22654843]]
Output:
 [[ 0.00242573]
 [-0.00282498]
 [-0.0004816 ]]

	( EPOCH 589 of 1000 )
h_ip:
 [[1.6243019  1.86267816 1.3078588 ]
 [1.29853017 1.36988166 1.10527433]
 [1.82952872 1.74560601 1.22655195]]
Output:
 [[ 0.0024273 ]
 [-0.00282394]
 [-0.00048038]]

	( EPOCH 590 of 1000 )
h_ip:
 [[1.62430441 1.8626782  1.30786351]
 [1.29853155 1.36988168 1.10527691]
 [1.82953065 1.74560605 1.22655553]]
Output:
 [[ 0.00242886]
 [-0.00282291]
 [-0.00047916]]

	( EPOCH 591 of 1000 )
h_ip:
 [[1.62430696 1.86267824 1.30786827]
 [1.29853295 1.3698817  1.10527952]
 [1.82953263 1.7456061  1.22655917]]
Output:
 [[ 0.00243041]
 [-0.00282188]
 [-0.00047795]]

	( EPOCH 592 of 1000 )
h_ip:
 [[1.62430956 1.86267828 1.30787309]
 [1.29853437 1.36988172 1.10528217]
 [1.82953465 1.74560614 1

 [1.82970148 1.74560748 1.22683906]]
Output:
 [[ 0.00250447]
 [-0.0027728 ]
 [-0.00042018]]

	( EPOCH 647 of 1000 )
h_ip:
 [[1.62451415 1.86267923 1.30821951]
 [1.29864574 1.3698822  1.10547118]
 [1.82970554 1.74560749 1.22684546]]
Output:
 [[ 0.00250563]
 [-0.00277203]
 [-0.00041928]]

	( EPOCH 648 of 1000 )
h_ip:
 [[1.62451889 1.86267922 1.30822714]
 [1.29864831 1.36988219 1.10547533]
 [1.82970963 1.74560749 1.2268519 ]]
Output:
 [[ 0.00250678]
 [-0.00277127]
 [-0.00041838]]

	( EPOCH 649 of 1000 )
h_ip:
 [[1.62452365 1.86267922 1.30823482]
 [1.29865089 1.36988219 1.10547951]
 [1.82971375 1.7456075  1.22685839]]
Output:
 [[ 0.00250793]
 [-0.0027705 ]
 [-0.00041748]]

	( EPOCH 650 of 1000 )
h_ip:
 [[1.62452845 1.86267922 1.30824254]
 [1.29865349 1.36988219 1.1054837 ]
 [1.8297179  1.7456075  1.22686491]]
Output:
 [[ 0.00250907]
 [-0.00276975]
 [-0.00041659]]

	( EPOCH 651 of 1000 )
h_ip:
 [[1.62453328 1.86267921 1.3082503 ]
 [1.29865611 1.36988219 1.10548792]
 [1.82972208 1.7456075  1

 [1.8304908  1.74560227 1.22802689]]
Output:
 [[ 0.00261647]
 [-0.00269775]
 [-0.00033237]]

	( EPOCH 784 of 1000 )
h_ip:
 [[1.62540227 1.86267248 1.30958159]
 [1.29912578 1.3698785  1.10620897]
 [1.8304979  1.7456022  1.22803735]]
Output:
 [[ 0.00261701]
 [-0.00269738]
 [-0.00033194]]

	( EPOCH 785 of 1000 )
h_ip:
 [[1.62541013 1.86267239 1.30959335]
 [1.29913003 1.36987845 1.10621533]
 [1.83050502 1.74560212 1.22804783]]
Output:
 [[ 0.00261755]
 [-0.00269701]
 [-0.00033151]]

	( EPOCH 786 of 1000 )
h_ip:
 [[1.62541801 1.8626723  1.30960513]
 [1.29913428 1.3698784  1.10622169]
 [1.83051216 1.74560204 1.22805832]]
Output:
 [[ 0.00261809]
 [-0.00269665]
 [-0.00033109]]

	( EPOCH 787 of 1000 )
h_ip:
 [[1.6254259  1.86267221 1.30961692]
 [1.29913853 1.36987835 1.10622807]
 [1.8305193  1.74560196 1.22806884]]
Output:
 [[ 0.00261863]
 [-0.00269629]
 [-0.00033067]]

	( EPOCH 788 of 1000 )
h_ip:
 [[1.6254338  1.86267211 1.30962874]
 [1.2991428  1.3698783  1.10623446]
 [1.83052647 1.74560188 1

	( EPOCH 859 of 1000 )
h_ip:
 [[1.62602845 1.86266447 1.31051169]
 [1.29946353 1.36987416 1.10671151]
 [1.83106734 1.74559518 1.22887021]]
Output:
 [[ 0.00265021]
 [-0.00267477]
 [-0.00030574]]

	( EPOCH 860 of 1000 )
h_ip:
 [[1.62603723 1.86266435 1.31052466]
 [1.29946827 1.3698741  1.10671851]
 [1.83107536 1.74559507 1.22888188]]
Output:
 [[ 0.00265056]
 [-0.00267452]
 [-0.00030546]]

	( EPOCH 861 of 1000 )
h_ip:
 [[1.62604603 1.86266423 1.31053765]
 [1.29947301 1.36987403 1.10672553]
 [1.83108338 1.74559496 1.22889356]]
Output:
 [[ 0.00265091]
 [-0.00267428]
 [-0.00030518]]

	( EPOCH 862 of 1000 )
h_ip:
 [[1.62605483 1.8626641  1.31055065]
 [1.29947775 1.36987396 1.10673255]
 [1.83109141 1.74559486 1.22890524]]
Output:
 [[ 0.00265126]
 [-0.00267404]
 [-0.0003049 ]]

	( EPOCH 863 of 1000 )
h_ip:
 [[1.62606364 1.86266398 1.31056366]
 [1.2994825  1.3698739  1.10673957]
 [1.83109945 1.74559475 1.22891695]]
Output:
 [[ 0.00265161]
 [-0.0026738 ]
 [-0.00030463]]

	( EPOCH 864 of 1000 )
h_

 [-0.00029288]]

	( EPOCH 913 of 1000 )
h_ip:
 [[1.62651548 1.86265744 1.31122892]
 [1.29972608 1.36987036 1.10709876]
 [1.83151242 1.74558891 1.22951641]]
Output:
 [[ 0.00266668]
 [-0.00266339]
 [-0.00029267]]

	( EPOCH 914 of 1000 )
h_ip:
 [[1.62652472 1.8626573  1.31124249]
 [1.29973106 1.36987029 1.10710609]
 [1.83152087 1.74558879 1.22952866]]
Output:
 [[ 0.00266694]
 [-0.00266321]
 [-0.00029247]]

	( EPOCH 915 of 1000 )
h_ip:
 [[1.62653397 1.86265716 1.31125607]
 [1.29973604 1.36987021 1.10711342]
 [1.83152934 1.74558866 1.22954092]]
Output:
 [[ 0.0026672 ]
 [-0.00266303]
 [-0.00029226]]

	( EPOCH 916 of 1000 )
h_ip:
 [[1.62654322 1.86265702 1.31126966]
 [1.29974103 1.36987014 1.10712076]
 [1.83153781 1.74558854 1.22955319]]
Output:
 [[ 0.00266746]
 [-0.00266285]
 [-0.00029206]]

	( EPOCH 917 of 1000 )
h_ip:
 [[1.62655248 1.86265688 1.31128326]
 [1.29974602 1.36987006 1.1071281 ]
 [1.83154628 1.74558842 1.22956546]]
Output:
 [[ 0.00266771]
 [-0.00266268]
 [-0.00029185]]

	( EPOCH

 [-0.00028495]]

	( EPOCH 956 of 1000 )
h_ip:
 [[1.62691872 1.86265128 1.31182025]
 [1.2999434  1.36986703 1.10741794]
 [1.83188179 1.74558338 1.23005077]]
Output:
 [[ 0.00267658]
 [-0.00265647]
 [-0.00028479]]

	( EPOCH 957 of 1000 )
h_ip:
 [[1.62692823 1.86265113 1.31183418]
 [1.29994852 1.36986695 1.10742546]
 [1.83189051 1.74558325 1.23006337]]
Output:
 [[ 0.00267678]
 [-0.00265633]
 [-0.00028463]]

	( EPOCH 958 of 1000 )
h_ip:
 [[1.62693775 1.86265098 1.31184811]
 [1.29995365 1.36986687 1.10743298]
 [1.83189923 1.74558312 1.23007597]]
Output:
 [[ 0.00267698]
 [-0.00265618]
 [-0.00028447]]

	( EPOCH 959 of 1000 )
h_ip:
 [[1.62694727 1.86265083 1.31186205]
 [1.29995878 1.36986679 1.1074405 ]
 [1.83190796 1.74558298 1.23008859]]
Output:
 [[ 0.00267718]
 [-0.00265604]
 [-0.00028431]]

	( EPOCH 960 of 1000 )
h_ip:
 [[1.6269568  1.86265068 1.311876  ]
 [1.29996392 1.36986671 1.10744803]
 [1.8319167  1.74558285 1.23010121]]
Output:
 [[ 0.00267738]
 [-0.0026559 ]
 [-0.00028415]]

	( EPOCH

In [10]:
print("Actual output: \n", y)
print("\nPredicted output: \n", output)

Actual output: 
 [[0.92]
 [0.86]
 [0.89]]

Predicted output: 
 [[0.89210975]
 [0.88630719]
 [0.89291257]]
