# Dheeraj J C - 1CR17CS036 (Prog 9)

Write a program to implement k-Nearest Neighbour algorithm to classify the iris data set. Print both correct and wrong predictions. Java/Python ML library classes can be used for this problem.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
X = iris.data
Y = iris.target
print("X\n", X[:5])
print("Y\n", Y[:5])

X
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Y
 [0 0 0 0 0]


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)
print(iris.data.shape)
print("\nLength of:")
print("X_train : ", len(X_train))
print("Y_train : ", len(Y_train))
print("X_test : ", len(X_test))
print("Y_test : ", len(Y_test))

(150, 4)

Length of:
X_train :  120
Y_train :  120
X_test :  30
Y_test :  30


In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=3)

In [7]:
Y_pred = knn.predict(X_test)
print(Y_pred)

[0 1 1 0 0 2 2 2 0 1 1 1 2 1 0 2 1 0 1 2 2 1 2 2 1 1 2 0 0 0]


In [8]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
print("Accuracy : ", metrics.accuracy_score(Y_pred, Y_test))
print("\n")
print(confusion_matrix(Y_test, Y_pred))
print("\n")
print(classification_report(Y_test, Y_pred))

Accuracy :  0.9666666666666667


[[ 9  0  0]
 [ 0 10  0]
 [ 0  1 10]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.91      1.00      0.95        10
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [9]:
predicted = knn.predict(X_test)
pre_target = [iris.target_names[i] for i in predicted]
print("Pre Target : ", pre_target, "\n\n")
actual_target = [iris.target_names[i] for i in Y_test]
print("Actual Target = ", actual_target, "\n\n")
print("\t Predicted\t\tActual\t\t\t\tAnswer")
print("-------------------------------------------------------------------------")
for i in range(0, len(pre_target)):
    print(i, ":", "\t", pre_target[i], "\t\t", actual_target[i], "\t\t", end="\t")
    if(pre_target[i] == actual_target[i]):
        print("Yes")
    else:
        print("No")

Pre Target :  ['setosa', 'versicolor', 'versicolor', 'setosa', 'setosa', 'virginica', 'virginica', 'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'versicolor', 'virginica', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa', 'setosa'] 


Actual Target =  ['setosa', 'versicolor', 'versicolor', 'setosa', 'setosa', 'virginica', 'virginica', 'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'virginica', 'virginica', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa', 'setosa'] 


	 Predicted		Actual				Answer
-------------------------------------------------------------------------
0 : 	 setosa 		 setosa 			Yes
1 : 	 versicolor 		 versicolor 			Yes
2 : 	 versicolor 		 versicolor 			Yes
3 : 

In [10]:
s1 = [X_test[2]]
s = knn.predict(s1)
print(s)
s2 = [Y_test[2]]
print(s2)
if s == s2 :
    print("Correct!")
else:
    print("Wrong!")

[1]
[1]
Correct!
